# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a0ba25b7d5d0b3eac001870de275476fdf0054b64c743dbd770c218d506a2abb2b7915df9acc70e4af8ae2109acda7925cc665e9b35f91cbb9bf32d2455941d

test:
  secret_key_base: 59ac39a1f0768814f8f3cf1cac405cf983df1075a285a2c024072bf608483328c4f8a49d86d6882625ae4d397f136dddb14d188d2ce1e3daa6fcf86ce9cb60f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
